const COMMITS = {
	LOAD: 'COMMITS_LOAD',
	LOAD_SUCCESS: 'COMMITS_LOAD_SUCCESS',
	LOAD_FAIL: 'COMMITS_LOAD_FAIL'
};

const BRANCHES = {
	LOAD: 'BRANCHES_LOAD',
	LOAD_SUCCESS: 'BRANCHES_LOAD_SUCCESS',
	LOAD_FAIL: 'BRANCHES_LOAD_FAIL',
	CURRENT: 'CURRENT_BRANCH'
};

const PULLS = {
	LOAD: 'PULLS_LOAD',
	LOAD_SUCCESS: 'PULLS_LOAD_SUCCESS',
	LOAD_FAIL: 'PULLS_LOAD_FAIL',
	CURRENT: 'CURRENT_STATE'
};
export { COMMITS, BRANCHES, PULLS };
