export const PULL_STATE = {
    OPEN:   'open',
    CLOSED: 'closed',
    ALL:    'all',
}

export const COMMITS = {
  LOAD: 'COMMITS_LOAD',
  LOAD_SUCCESS: 'COMMITS_LOAD_SUCCESS',
  LOAD_FAIL: 'COMMITS_LOAD_FAIL'
};

export const BRANCHES = {
  LOAD: 'BRANCHES_LOAD',
  LOAD_SUCCESS: 'BRANCHES_LOAD_SUCCESS',
  LOAD_FAIL: 'BRANCHES_LOAD_FAIL'
};

export const PULLS = {
  LOAD: 'PULLS_LOAD',
  LOAD_SUCCESS: 'PULLS_LOAD_SUCCESS',
  LOAD_FAIL: 'PULLS_LOAD_FAIL'
};

export const BUILD_DATA = {
  LOAD: 'BUILD_DATA_LOAD',
  LOAD_SUCCESS: 'BUILD_DATA_LOAD_SUCCESS',
  LOAD_FAIL: 'BUILD_DATA_LOAD_FAIL'
};

export const TESTMAN_DATA = {
  LOAD: 'TESTMAN_DATA_LOAD',
  LOAD_SUCCESS: 'TESTMAN_DATA_LOAD_SUCCESS',
  LOAD_FAIL: 'TESTMAN_DATA_LOAD_FAIL'
};

export const BUILDERS = {
  LOAD: 'BUILDER_LOAD',
  LOAD_SUCCESS: 'BUILDER_LOAD_SUCCESS',
  LOAD_FAIL: 'BUILDER_LOAD_FAIL'
};
