const COMMITS = {
	LOAD: 'COMMITS_LOAD',
	LOAD_SUCCESS: 'COMMITS_LOAD_SUCCESS',
	LOAD_FAIL: 'COMMITS_LOAD_FAIL'
};

const BRANCHES = {
	LOAD: 'BRANCHES_LOAD',
	LOAD_SUCCESS: 'BRANCHES_LOAD_SUCCESS',
	LOAD_FAIL: 'BRANCHES_LOAD_FAIL',
	CURRENT: 'CURRENT_BRANCH'
};

export { COMMITS, BRANCHES };
